---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.fullname }}
  labels:
    app: {{ .Values.deployment.fullname }}
    {{- with .Values.deployment.labels}}
    {{- toYaml . | nindent 4  }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.fullname }}
      {{- with .Values.deployment.selectorLabels}}
      {{- toYaml . | nindent 4  }}
      {{- end }}
  template:
    {{- if or (.Values.deployment.podAnnotations) (.Values.deployment.podLabels)}}
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.deployment.fullname }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.deployment.fullname }}
          {{- with .Values.deployment.image.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          {{- with .Values.deployment.image.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: {{ .Values.deployment.image.command }}
          args: {{ .Values.deployment.image.args }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
