---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-tools
  labels:
    app: net-tools
spec:
  selector:
    matchLabels:
      app: net-tools
  template:
    metadata:
      labels:
        app: net-tools
    spec:
      containers:
        - name: net-tools
          image: corpheus91/net-tools:bookworm-slim
          imagePullPolicy: IfNotPresent
          command: [sleep]
          args: [infinity]

