# This is a basic workflow to help you get started with Actions

name: Publish Net-Tools Helm Chart

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/publish_net-tools_chart.yml
      - helm/net-tools/Chart.yaml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build_net-tools.yml
      - helm/net-tools/Chart.yaml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DISTRIBUTION: "bookworm"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  publish_chart:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish Chart
      shell: bash
      run: |

        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

        cd helm
        helm package net-tools

        NET_TOOLS_PACKAGE=$(find . -name "*.tgz" | xargs basename)

        echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
        
        helm push $NET_TOOLS_PACKAGE  oci://registry-1.docker.io/${{ secrets.DOCKERHUB_TOKEN }} 